//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.BAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Training.BAL.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was catched..
        /// </summary>
        internal static string LogErrorExeptionCatched {
            get {
                return ResourceManager.GetString("LogErrorExeptionCatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\nError:{1}\nMessage:{2}.
        /// </summary>
        internal static string LogErrorExeptionMessage {
            get {
                return ResourceManager.GetString("LogErrorExeptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0} was created..
        /// </summary>
        internal static string LogUserCreated {
            get {
                return ResourceManager.GetString("LogUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating User: {0}.
        /// </summary>
        internal static string LogUserCreating {
            get {
                return ResourceManager.GetString("LogUserCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id: {0} was deleted..
        /// </summary>
        internal static string LogUserDeleted {
            get {
                return ResourceManager.GetString("LogUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting User with id: {0}.
        /// </summary>
        internal static string LogUserDeleting {
            get {
                return ResourceManager.GetString("LogUserDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id: {0} was found..
        /// </summary>
        internal static string LogUserFound {
            get {
                return ResourceManager.GetString("LogUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting User with id: {0}.
        /// </summary>
        internal static string LogUserGetting {
            get {
                return ResourceManager.GetString("LogUserGetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserService instance was created..
        /// </summary>
        internal static string LogUserServiceCreated {
            get {
                return ResourceManager.GetString("LogUserServiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating UserService instance..
        /// </summary>
        internal static string LogUserServiceCreating {
            get {
                return ResourceManager.GetString("LogUserServiceCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users were found..
        /// </summary>
        internal static string LogUsersFound {
            get {
                return ResourceManager.GetString("LogUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geting all users..
        /// </summary>
        internal static string LogUsersGetting {
            get {
                return ResourceManager.GetString("LogUsersGetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id: {0} was updated..
        /// </summary>
        internal static string LogUserUpdated {
            get {
                return ResourceManager.GetString("LogUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating User with id: {0}.
        /// </summary>
        internal static string LogUserUpdating {
            get {
                return ResourceManager.GetString("LogUserUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Name &quot;{0}&quot; is already exist!.
        /// </summary>
        internal static string UserResponseErrorMessage {
            get {
                return ResourceManager.GetString("UserResponseErrorMessage", resourceCulture);
            }
        }
    }
}
